version: '3'
services:
  springboot:
    image: openjdk:17
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: springboot.dockerfile
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:log4jdbc:mysql://mysql:3306/laf?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
  mysql:
    image: mysql:8
    build:
      context: .
      dockerfile: mysql.dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: laf
    ports:
      - "3306:3306"
